---
abstract: "Interface to Adobe SiteCatalyst's REST API."
author:
  - 'Jennifer Pinkham <jpinkham@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  Data::Validate::Type: 1.001000
  DateTime: 0
  Digest::MD5: 0
  Digest::SHA1: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Test::More: 0.94
  Try::Tiny: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-SiteCatalyst
provides:
  Business::SiteCatalyst:
    file: lib/Business/SiteCatalyst.pm
    version: v1.0.0
  Business::SiteCatalyst::Report:
    file: lib/Business/SiteCatalyst/Report.pm
    version: v1.0.0
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Business-SiteCatalyst
  homepage: https://metacpan.org/release/Business-SiteCatalyst
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://sourceforge.net/p/perlscreport/code
version: v1.0.0
